# Generated by Django 5.0.7 on 2024-07-14 00:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=100, verbose_name='Título (portada)')),
                ('hero_date', models.CharField(max_length=50, verbose_name='Fecha (portada)')),
                ('hero_place', models.CharField(max_length=100, verbose_name='Lugar (portada)')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio del evento')),
                ('body_title', models.CharField(max_length=100, verbose_name='Título')),
                ('body_date', models.CharField(max_length=50, verbose_name='Fecha')),
                ('body_modality', models.CharField(max_length=30, verbose_name='Modalidad')),
                ('body_content', ckeditor.fields.RichTextField(verbose_name='Contenido del cuerpo')),
                ('aside_content', ckeditor.fields.RichTextField(verbose_name='Contenido de la barra lateral')),
                ('cta', models.URLField(verbose_name='Enlace del programa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Inicio',
                'verbose_name_plural': 'Inicio',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='Nombre del sitio')),
                ('site_logo', models.ImageField(upload_to='core', verbose_name='Logo del sitio')),
                ('navbar_logo', models.ImageField(upload_to='core', verbose_name='Logo de la barra de navegación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
