# Generated by Django 5.0.7 on 2024-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='aside_title',
            field=models.CharField(default=None, max_length=80, verbose_name='Título de la barra lateral'),
            preserve_default=False,
        ),
    ]
