# Generated by Django 5.0.7 on 2024-07-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_home_aside_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('link_CA', models.URLField(blank=True, null=True, verbose_name='Web de Computo Distribuido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('social_facebook', models.URLField(verbose_name='Facebook')),
                ('social_youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='core', verbose_name='Imagen del encabezado')),
                ('footer_image', models.ImageField(upload_to='core', verbose_name='Imagen del pie')),
                ('left_title', models.CharField(max_length=40, verbose_name='Título izquierdo')),
                ('left_description', models.CharField(max_length=40, verbose_name='Descripción izquierda')),
                ('left_cta', models.URLField(verbose_name='Enlace del boton izquierdo')),
                ('right_title', models.CharField(max_length=40, verbose_name='Título derecho')),
                ('right_description', models.CharField(max_length=40, verbose_name='Descripción derecha')),
                ('right_cta', models.URLField(verbose_name='Enlace del boton derecho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Modal',
                'verbose_name_plural': 'Modal',
            },
        ),
    ]
